#!/usr/bin/env bash
#$ -wd /home/kitsing/scratch/data/2020/task1/baselines/fst
#$ -l ram_free=80G,mem_free=80G
#$ -V
#$ -N gen_best_hyps
#$ -j y -o $JOB_NAME-$JOB_ID.out
#$ -M clin103@jhu.edu
#$ -m e

conda activate task1

set -eou pipefail
readonly LANG=${1}

main() {
    local -r BEST_RUN="$(python gen_best_hyps.py --checkpoint-prefix checkpoint-dakshina --language ${LANG})"
    cut -f2 ../../data_dakshina/dev/${LANG}_dev.tsv > checkpoints-dakshina/inputs/${LANG}_dev
    ./reranking_scripts/gen_hyps.py                                   \
        --input-path checkpoints-dakshina/inputs/${LANG}_dev                   \
        --output-path checkpoints-dakshina/hyps/${LANG}_dev.hyps \
        --invert \
        --input-token-type="symbols/${LANG}.phones.sym"   \
        --fst-path checkpoints-dakshina/${LANG}-${BEST_RUN}.fst --cores 8
}

main
