#!/usr/bin/env bash
#$ -wd /home/kitsing/scratch/data/2020/task1/baselines/fst
#$ -l ram_free=15G,mem_free=15G
#$ -V
#$ -N wfstbaseline
#$ -j y -o $JOB_NAME-$JOB_ID.out
#$ -M clin103@jhu.edu
#$ -m e

conda activate task1

set -eou pipefail

readonly SEED=1917
readonly DAKSHINA_DATA=/export/b08/kitsing/dakshina/dakshina_dataset_v1.0
readonly DATA=../../data_dakshina
readonly RANDOM_STARTS=1
readonly LANG=${1}
mkdir -p checkpoints-dakshina/hyps
mkdir -p ${DATA}

TRAIN_TSV="${DATA}/train/${LANG}_train.tsv"
DEV_TSV="${TRAIN_TSV//train/dev}"
TEST_TSV="${TRAIN_TSV//train/test}"
LANGUAGE="$(basename $TRAIN_TSV _train.tsv)"

for ORDER in $(seq 3 9); do

    ./crunch \
        --input_path="${DEV_TSV}" \
        --fst_path="checkpoints-dakshina/${LANGUAGE}-${ORDER}.fst" \
        --input_token_type="symbols/${LANGUAGE}.phones.sym" \
        --output_path="checkpoints-dakshina/hyps/${LANGUAGE}-${ORDER}.hyps.txt.invert" \
        -i

    ./crunch \
        --input_path="${TEST_TSV}" \
        --fst_path="checkpoints-dakshina/${LANGUAGE}-${ORDER}.fst" \
        --input_token_type="symbols/${LANGUAGE}.phones.sym" \
        -i \
        --output_path="checkpoints-dakshina/hyps/${LANGUAGE}-${ORDER}.hyps.txt.test.invert"

done

